/**
 * Health Plan store — manages active and historical health plans.
 *
 * Plans are generated by the AI planner service or created manually.
 * Each plan contains a weekly schedule of workouts, meals, protocols, and check-ins.
 */

import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import { secureStorage } from '../services/secureStorage';
import type { HealthPlan, HealthPlanItem, GoalType } from '../types';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const uid = () =>
  `plan-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;

const itemUid = () =>
  `item-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`;

const toDateKey = (d: Date) => {
  const y = d.getFullYear();
  const m = `${d.getMonth() + 1}`.padStart(2, '0');
  const dd = `${d.getDate()}`.padStart(2, '0');
  return `${y}-${m}-${dd}`;
};

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface PlanState {
  /** Currently active plan */
  activePlan: HealthPlan | null;
  /** History of completed/archived plans */
  planHistory: HealthPlan[];
}

interface PlanActions {
  /** Create and activate a new plan */
  createPlan: (input: {
    name: string;
    goals: GoalType[];
    durationWeeks: number;
    schedule: Omit<HealthPlanItem, 'id' | 'completed'>[];
    aiGenerated?: boolean;
    rawPlanText?: string;
  }) => HealthPlan;

  /** Create plan from raw AI text (minimal structured schedule) */
  createPlanFromAI: (input: {
    name: string;
    goals: GoalType[];
    durationWeeks: number;
    rawPlanText: string;
  }) => HealthPlan;

  /** Mark a schedule item as completed */
  completeItem: (itemId: string) => void;

  /** Un-complete a schedule item */
  uncompleteItem: (itemId: string) => void;

  /** Add an item to the active plan */
  addItem: (item: Omit<HealthPlanItem, 'id' | 'completed'>) => void;

  /** Remove an item from the active plan */
  removeItem: (itemId: string) => void;

  /** Archive the active plan and clear it */
  archivePlan: () => void;

  /** Delete the active plan without archiving */
  deletePlan: () => void;

  /** Get today's schedule items from the active plan */
  getTodayItems: () => HealthPlanItem[];

  /** Get items for a specific day of week */
  getItemsByDay: (dayOfWeek: number) => HealthPlanItem[];

  /** Get completion percentage for this week */
  getWeeklyProgress: () => number;

  /** Clear all data */
  clearAll: () => void;
}

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

export const usePlanStore = create<PlanState & PlanActions>()(
  persist(
    (set, get) => ({
      activePlan: null,
      planHistory: [],

      createPlan: (input) => {
        const now = new Date();
        const endDate = new Date(now);
        endDate.setDate(endDate.getDate() + input.durationWeeks * 7);

        const plan: HealthPlan = {
          id: uid(),
          name: input.name,
          startDate: toDateKey(now),
          endDate: toDateKey(endDate),
          goals: input.goals,
          schedule: input.schedule.map((item) => ({
            ...item,
            id: itemUid(),
            completed: false,
          })),
          aiGenerated: input.aiGenerated ?? false,
          rawPlanText: input.rawPlanText,
          createdAt: now.toISOString(),
          updatedAt: now.toISOString(),
        };

        // Archive existing active plan if any
        const { activePlan } = get();
        set((state) => ({
          activePlan: plan,
          planHistory: activePlan
            ? [activePlan, ...state.planHistory]
            : state.planHistory,
        }));

        return plan;
      },

      createPlanFromAI: (input) => {
        // Create a plan with the raw text and a basic daily check-in schedule
        const defaultSchedule: Omit<HealthPlanItem, 'id' | 'completed'>[] = [
          { dayOfWeek: 1, time: '07:00', type: 'checkin', title: 'Morning Check-In', description: 'Log mood, energy, and sleep quality' },
          { dayOfWeek: 2, time: '07:00', type: 'checkin', title: 'Morning Check-In', description: 'Log mood, energy, and sleep quality' },
          { dayOfWeek: 3, time: '07:00', type: 'checkin', title: 'Morning Check-In', description: 'Log mood, energy, and sleep quality' },
          { dayOfWeek: 4, time: '07:00', type: 'checkin', title: 'Morning Check-In', description: 'Log mood, energy, and sleep quality' },
          { dayOfWeek: 5, time: '07:00', type: 'checkin', title: 'Morning Check-In', description: 'Log mood, energy, and sleep quality' },
          { dayOfWeek: 6, time: '07:00', type: 'checkin', title: 'Morning Check-In', description: 'Log mood, energy, and sleep quality' },
          { dayOfWeek: 0, time: '07:00', type: 'checkin', title: 'Morning Check-In', description: 'Log mood, energy, and sleep quality' },
        ];

        return get().createPlan({
          name: input.name,
          goals: input.goals,
          durationWeeks: input.durationWeeks,
          schedule: defaultSchedule,
          aiGenerated: true,
          rawPlanText: input.rawPlanText,
        });
      },

      completeItem: (itemId) => {
        set((state) => {
          if (!state.activePlan) return state;
          return {
            activePlan: {
              ...state.activePlan,
              updatedAt: new Date().toISOString(),
              schedule: state.activePlan.schedule.map((item) =>
                item.id === itemId ? { ...item, completed: true } : item
              ),
            },
          };
        });
      },

      uncompleteItem: (itemId) => {
        set((state) => {
          if (!state.activePlan) return state;
          return {
            activePlan: {
              ...state.activePlan,
              updatedAt: new Date().toISOString(),
              schedule: state.activePlan.schedule.map((item) =>
                item.id === itemId ? { ...item, completed: false } : item
              ),
            },
          };
        });
      },

      addItem: (item) => {
        set((state) => {
          if (!state.activePlan) return state;
          return {
            activePlan: {
              ...state.activePlan,
              updatedAt: new Date().toISOString(),
              schedule: [
                ...state.activePlan.schedule,
                { ...item, id: itemUid(), completed: false },
              ],
            },
          };
        });
      },

      removeItem: (itemId) => {
        set((state) => {
          if (!state.activePlan) return state;
          return {
            activePlan: {
              ...state.activePlan,
              updatedAt: new Date().toISOString(),
              schedule: state.activePlan.schedule.filter((i) => i.id !== itemId),
            },
          };
        });
      },

      archivePlan: () => {
        const { activePlan } = get();
        if (!activePlan) return;
        set((state) => ({
          activePlan: null,
          planHistory: [activePlan, ...state.planHistory],
        }));
      },

      deletePlan: () => {
        set({ activePlan: null });
      },

      getTodayItems: () => {
        const { activePlan } = get();
        if (!activePlan) return [];
        const today = new Date().getDay();
        return activePlan.schedule.filter((item) => item.dayOfWeek === today);
      },

      getItemsByDay: (dayOfWeek) => {
        const { activePlan } = get();
        if (!activePlan) return [];
        return activePlan.schedule.filter((item) => item.dayOfWeek === dayOfWeek);
      },

      getWeeklyProgress: () => {
        const { activePlan } = get();
        if (!activePlan || activePlan.schedule.length === 0) return 0;
        const completed = activePlan.schedule.filter((i) => i.completed).length;
        return Math.round((completed / activePlan.schedule.length) * 100);
      },

      clearAll: () => set({ activePlan: null, planHistory: [] }),
    }),
    {
      name: 'peptalk-plans',
      storage: createJSONStorage(() => secureStorage),
      partialize: (state) => ({
        activePlan: state.activePlan,
        planHistory: state.planHistory,
      }),
    },
  ),
);

export default usePlanStore;
